name: "coloc"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    profiles:
      - dev
      - deploy

  adminer:
    profiles:
      - dev
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build: ./front
    restart: always
    ports:
      - "3000:80"
    profiles:
      - deploy

  backend:
    build: ./back
    restart: always
    ports:
      - "5000:3000"
    depends_on:
      - db
    profiles:
      - deploy



volumes:
  postgres_data: