services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    profiles:
      - dev
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  postgres_data: