DROP TABLE IF EXISTS tblSojourn;
DROP TABLE IF EXISTS tblPayment;
DROP TABLE IF EXISTS tblAbundance;
DROP TABLE IF EXISTS tblAchat;
DROP TABLE IF EXISTS tblPot;
DROP TABLE IF EXISTS tblPerson;
DROP TABLE IF EXISTS tblColocation;
