name: Docker Image CI

on:
  push:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    -
        name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
    -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    -
        name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:front"
          push: true
          tags: ghcr.io/rois2coeurs/coloc:latest
          platforms: linux/amd64,linux/arm64
    -
        name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:back"
          push: true
          tags: ghcr.io/rois2coeurs/coloc:latest
          platforms: linux/amd64,linux/arm64
    
